# Copy to .github/workflows/release.yml in the consuming repository.
name: Create Release ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    uses: PineappleEmperor/ha-integration-ci/.github/workflows/release.yml@ae1131548e7428e9e18dff179269ad29dbaa0bb8 # v1.0.0rc1
